config: !!python/object:src.config.Config
  __dict__:
    accelerator: gpu
    data_config: !!python/object:src.config.DataConfig
      __dict__:
        batch_size: 8
        data_path: ./data_sports
        height: 224
        n_workers: 4
        train_size: 0.7
        width: 224
      __fields_set__: !!set
        batch_size: null
        data_path: null
        height: null
        n_workers: null
        train_size: null
        width: null
      __private_attribute_values__: {}
    device: 0
    experiment_name: resnet18_COMB_aug
    losses:
    - !!python/object:src.config.LossConfig
      __dict__:
        loss_fn: torch.nn.CrossEntropyLoss
        name: CE
        weight: 1.0
      __fields_set__: !!set
        loss_fn: null
        name: null
        weight: null
      __private_attribute_values__: {}
    metrics_average: macro
    model_kwargs:
      model_name: resnet18.a1_in1k
      pretrained: true
    monitor_metric: val_f1
    monitor_mode: max
    n_epochs: 30
    num_classes: 30
    optimizer: torch.optim.AdamW
    optimizer_kwargs:
      lr: 0.001
      weight_decay: 1.0e-05
    project_name: ButterflyClassifier
    scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
    scheduler_kwargs:
      factor: 0.3
      min_lr: 1.0e-05
      mode: min
      patience: 10
    threshold: 0.5
  __fields_set__: !!set
    accelerator: null
    data_config: null
    device: null
    experiment_name: null
    losses: null
    metrics_average: null
    model_kwargs: null
    monitor_metric: null
    monitor_mode: null
    n_epochs: null
    num_classes: null
    optimizer: null
    optimizer_kwargs: null
    project_name: null
    scheduler: null
    scheduler_kwargs: null
    threshold: null
  __private_attribute_values__: {}
label_names: []
