__version__: 1.3.1
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  is_check_shapes: true
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: Compose
    additional_targets: {}
    bbox_params: null
    is_check_shapes: true
    keypoint_params: null
    p: 1.0
    transforms:
    - __class_fullname__: CLAHE
      always_apply: false
      clip_limit:
      - 1
      - 4.0
      p: 0.5
      tile_grid_size:
      - 8
      - 8
    - __class_fullname__: RandomBrightnessContrast
      always_apply: false
      brightness_by_max: true
      brightness_limit:
      - -0.3
      - 0.3
      contrast_limit:
      - -0.3
      - 0.3
      p: 0.5
    - __class_fullname__: HueSaturationValue
      always_apply: false
      hue_shift_limit:
      - -20
      - 20
      p: 0.6
      sat_shift_limit:
      - -30
      - 30
      val_shift_limit:
      - -20
      - 20
    - __class_fullname__: GaussNoise
      always_apply: false
      mean: 0
      p: 0.5
      per_channel: true
      var_limit:
      - 10.0
      - 50.0
    - __class_fullname__: OneOf
      p: 0.2
      transforms:
      - __class_fullname__: MotionBlur
        allow_shifted: true
        always_apply: false
        blur_limit:
        - 3
        - 7
        p: 0.2
      - __class_fullname__: MedianBlur
        always_apply: false
        blur_limit:
        - 3
        - 3
        p: 0.1
      - __class_fullname__: Blur
        always_apply: false
        blur_limit:
        - 3
        - 3
        p: 0.1
  - __class_fullname__: Compose
    additional_targets: {}
    bbox_params: null
    is_check_shapes: true
    keypoint_params: null
    p: 1.0
    transforms:
    - __class_fullname__: HorizontalFlip
      always_apply: false
      p: 0.5
    - __class_fullname__: ShiftScaleRotate
      always_apply: false
      border_mode: 4
      interpolation: 1
      mask_value: null
      p: 0.5
      rotate_limit:
      - -30
      - 30
      rotate_method: largest_box
      scale_limit:
      - -0.30000000000000004
      - 0.30000000000000004
      shift_limit_x:
      - -0.0625
      - 0.0625
      shift_limit_y:
      - -0.0625
      - 0.0625
      value: null
    - __class_fullname__: RandomResizedCrop
      always_apply: false
      height: 224
      interpolation: 1
      p: 0.5
      ratio:
      - 0.8
      - 1.2
      scale:
      - 0.5
      - 1.0
      width: 224
